I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 79, in script
    m "Wax swallows forcefully."
Exception: Sayer 'm' is not defined.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 79, in script
    m "Wax swallows forcefully."
  File "/Users/dansienko/Desktop/renpy-8.3.7-sdk/renpy/ast.py", line 2586, in execute
    Say.execute(self)
  File "/Users/dansienko/Desktop/renpy-8.3.7-sdk/renpy/ast.py", line 583, in execute
    who = eval_who(self.who, self.who_fast)
  File "/Users/dansienko/Desktop/renpy-8.3.7-sdk/renpy/ast.py", line 472, in eval_who
    raise Exception("Sayer '%s' is not defined." % who)
Exception: Sayer 'm' is not defined.

macOS-14.6.1-arm64-arm-64bit arm64
Ren'Py 8.3.7.25031702
Exploration 4 1.0
Mon May  5 22:13:45 2025
